[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cuda-stubs"
version = "0.0.1"

[tool.hatch.build.targets.sdist]
include = [
    "/cuda-stubs",
]

[tool.hatch.build.targets.wheel]
include = [
    "/cuda-stubs",
]
